name 'wazuh_server'
maintainer 'Jon DeCamp (OCI CaaS)'
maintainer_email 'jon.dcamp@oracle.com'
license          'Apache 2.0'
description 'Installs/Configures wazuh_server'
version '0.5.2'
chef_version '>= 16.0'

depends 'oci_caas_base'
depends 'apt'
depends 'poise-python'
depends 'yum'
depends 'hostsfile'
depends 'htpasswd'
depends 'firewalld'
depends 'selinux'
depends 'tar'

issues_url 'https://github.com/oracle-quickstart/oci-caas-wazuh-server/issues'
source_url 'https://github.com/oracle-quickstart/oci-caas-wazuh-server'